### ISSUE TITLE
Create Content Negotiation Tutorial

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/phoenix-content-negotiation-tutorial#1]
Our goal with the @dwyl App is to have a server-side rendered (and progressively enhanced) Web UI (`HTML`) that works on _any_ device and a REST API (`JSON`) that can be _consumed programmatically_ by any script/system/app. We want the **`default`** UX (the Web) to be _great_ ***and*** we want the API to be available from ["**Day 1**"](https://youtu.be/fTwXS2H_iJo). We _definitely_ don't want to create/maintain two _separate_ Phoenix Apps. We don't even want to maintain two separate router _pipelines_. We want the **_same_ route** to _transparently_ return a different _representation_ of the content dependent on the `Accepts` header.

# Todo

+ [x] Create a tutorial that builds an App from scratch that:
  + [x] Returns a _random_ famous quotation on the `GET /` request.
  + [x] Render `HTML` if the `Accepts` header is `text/html`
  + [x] Render `JSON` if the `Accepts` header is `application/json`

Read and understand the following:
+ [x] MDN Article: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation
+ [x] Chris's gist: https://gist.github.com/chrismccord/31340f08d62de1457454 (pattern matching)
+ [x] Issue thread with more detail: https://github.com/phoenixframework/phoenix/issues/1054

**Comment by nelsonic** [comment]
Seeing this error:
```
     ** (ArgumentError) a content-type header is required when setting a binary body in a test connection
```
Will investigate when I get back to my desk.

**Comment by nelsonic** [comment]
Derp ... 🤦 
Can you spot what is wrong with this code:
```elixir
defmodule AppWeb.PageControllerTest do
  use AppWeb.ConnCase

  test "GET /", %{conn: conn} do
    conn =
      conn
      |> put_req_header("accept", "text/html")
      |> get(conn, "/")

    assert html_response(conn, 200) =~ "Welcome to Phoenix!"
  end
end
```
If you can, great! If not, don't worry, it's subtle! See the commit that fixed the test: https://github.com/dwyl/phoenix-content-negotiation-tutorial/commit/7fc61bc9d2071072e94a0e9e41ffcb258171a576

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/82154438-d4f27600-9865-11ea-926e-18e77e8b45bf.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/82154449-f5223500-9865-11ea-975e-4bb4c020577c.png)

**Comment by nelsonic** [comment]
Terminal JSON on `localhost`:
![enthusiasm-terminal-quote](https://user-images.githubusercontent.com/194400/82190805-7ff84380-98e9-11ea-8159-e13ea3a44a01.png)

**Comment by nelsonic** [comment]
I'm fairly happy with the tutorial: https://github.com/dwyl/phoenix-content-negotiation-tutorial
(_feedback and improvements very much welcome!_)

_Now_ I'm working on _generalising_ the solution in a Plug so that _any_ App can do this with _minimal_ code: https://github.com/dwyl/content_negotiation_plug

🧑‍💻
